### ISSUE TITLE
tabs no longer responding on property tax map

### ISSUE THREAD

**Issue by meli-lewis** [TheOregonian/data-guide#1]
## Expected

When I select a tab on http://projects.oregonlive.com/taxes/property/change/, I will see a view for that tab.
## Actual

I select the tab and see no response, either in the image or in the tab seemingly selected.
## System info

_Computer_: Mid 2013 Macbook Air
_Operating system_: OS 10.11.16
_Browser_: Google Chrome Version 53.0.2785.116

**Comment by stevesuo** [comment]
Phooey! Weird. Friesen will know what to do .

**Comment by mpfriesen** [comment]
Some issue with the placement of the script reference to the Metro Autosuggest API. The address search wasn't working, either. Moving the script reference from the bottom of the file to the HTML head seems to have fixed it.
